### ISSUE TITLE
Translations and data from blitzortung.org directly

### ISSUE THREAD

**Issue by karevivan** [wuan/bo-android#183]
Data from blitzortung.org directly don't showing.
Some text don't translating (red marker on screenshot).
![screenshot_20190206-092029](https://user-images.githubusercontent.com/39244508/52325920-e2c91280-29f7-11e9-91d8-9d35da27b666.png)
![sketch-1549434246874](https://user-images.githubusercontent.com/39244508/52325918-e197e580-29f7-11e9-8757-826c3c645fef.png)
![sketch-1548827729095](https://user-images.githubusercontent.com/39244508/52325919-e2307c00-29f7-11e9-9b69-f4df699828fa.png)

**Comment by wuan** [comment]
Should be fixed on master (Beta version 2.0.3). Please use multiple issues for different topics.

**Comment by karevivan** [comment]
Ok. 
Translation fixed.

Data from blitzortung.org directly still don't work on v2.0.3 (223).

**Comment by wuan** [comment]
Please check you credentials and the application log. The basic problem was that Apps for API level 28 (Android P) are not allowed to do plaintext HTTP requests by default. This is fixed in 2.0.3 and it works:
![screenshot_20190210-090207](https://user-images.githubusercontent.com/563314/52531334-afe28f80-2d13-11e9-93af-f03b576b6aee.png)

**Comment by karevivan** [comment]
If you choose to send data from the default source, the strikes are displayed normally, but if you select a data source from blitzortung.org the data is not received and is not displayed.
![screenshot_20190210-111707](https://user-images.githubusercontent.com/39244508/52531511-b5e26b80-2d27-11e9-95be-683b718e33e5.png)
![screenshot_20190210-111734](https://user-images.githubusercontent.com/39244508/52531510-b5e26b80-2d27-11e9-808a-6881e0fb3e60.png)
![screenshot_20190210-111726](https://user-images.githubusercontent.com/39244508/52531512-b5e26b80-2d27-11e9-9024-645a99339c02.png)
```
Version 2.0.3 (223)

Device: D5803, model: D5803, Product: D5803, Version: 3.4.0-perf-gc14c2d5, SDK: 23

--------- beginning of main
02-10 11:16:45.395 26391 26412 I chatty  : uid=10449(org.blitzortung.android.app) pool-1-thread-2 expire 1 line
02-10 11:16:45.517 26391 26400 I chatty  : uid=10449(org.blitzortung.android.app) HeapTaskDaemon expire 1 line
02-10 11:16:45.544 26391 29368 I chatty  : uid=10449(org.blitzortung.android.app) downloader expire 1 line
02-10 11:16:48.491 26391 26409 I chatty  : uid=10449(org.blitzortung.android.app) pool-1-thread-1 expire 1 line
02-10 11:16:48.643 26391 29372 I chatty  : uid=10449(org.blitzortung.android.app) AsyncTask #1 expire 33 lines
02-10 11:16:48.659 26391 26391 I chatty  : uid=10449(org.blitzortung.android.app) expire 11 lines
02-10 11:16:51.108 26391 26391 W art     : Before Android 4.1, method int android.support.v7.widget.MenuPopupWindow$MenuDropDownListView.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
02-10 11:16:51.144 26391 26391 V BO_ANDROID: MainPopupMenu.showPopupMenu()
02-10 11:16:54.203 26391 26391 D BO_ANDROID: updateVersionStatus() name=org.blitzortung.android.app, state=NO_UPDATE, configuredVersion=223, currentVersion=223
02-10 11:16:54.204 26391 26391 I Timeline: Timeline: Activity_launch_request id:org.blitzortung.android.app time:499330855
02-10 11:16:54.210 26391 26391 V BO_ANDROID: Main.onPause()
02-10 11:16:54.210 26391 26391 D BO_ANDROID: AlertHandler: removed last alert consumer
02-10 11:16:54.210 26391 26391 D BO_ANDROID: DataHandler: removed last data consumer
02-10 11:16:54.213 26391 26391 I BO_ANDROID: LocationHandler.sendLocationUpdate() location null
02-10 11:16:54.213 26391 26391 V BO_ANDROID: AlertHandler: received location null (was Location[network 55,981607,37,179575 acc=23 et=+19d13h7m19s975ms alt=0.0 vel=0.0 bear=0.0 {Bundle[mParcelledData.dataSize=80]}])
02-10 11:16:54.215 26391 26391 V BO_ANDROID: LocationProvider.shutdown() type: network
02-10 11:16:54.215 26391 26413 V BO_ANDROID: AlertHandler.checkStrikes() strikes: false, location: false
02-10 11:16:54.215 26391 26391 V BO_ANDROID: AppService.configureServiceMode() disable_bg
02-10 11:16:54.215 26391 26391 V BO_ANDROID: Main.stopDataUpdates() remove listeners
02-10 11:16:54.215 26391 26391 V BO_ANDROID: HistoryController.setAppService(null)
02-10 11:16:54.216 26391 26391 V BO_ANDROID: Main.onPause() 2019-02-10 11:16:54.216
02-10 11:16:54.230 26391 26391 V BO_ANDROID: AlertHandler.processResult() no result 
02-10 11:16:54.230 26391 26391 V BO_ANDROID: AlertHandler.broadcastEvent(AlertCancelEvent())
02-10 11:16:54.411 26391 26422 D OpenGLRenderer: endAllActiveAnimators on 0x9b7a2e00 (MenuPopupWindow$MenuDropDownListView) with handle 0x9c9abbc0
02-10 11:16:54.417 26391 26391 I Timeline: Timeline: Activity_idle id: android.os.BinderProxy@2dbaa32 time:499331069
02-10 11:16:54.566 26391 26391 V BO_ANDROID: Main.onStop()
02-10 11:16:54.566 26391 26391 V BO_ANDROID: Main.onStop() 2019-02-10 11:16:54.566
02-10 11:17:11.249 26391 26391 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
02-10 11:17:16.060 26391 26391 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
02-10 11:17:18.666 26391 26391 D BO_ANDROID: Main.onRestart() 2019-02-10 11:17:18.665 service: org.blitzortung.android.app.AppService@7dcd617
02-10 11:17:18.666 26391 26391 V BO_ANDROID: Main.onStart()
02-10 11:17:18.667 26391 26391 V BO_ANDROID: Main.onStart() # of overlays 1
02-10 11:17:18.667 26391 26391 D BO_ANDROID: Main.onStart() service: org.blitzortung.android.app.AppService@7dcd617
02-10 11:17:18.667 26391 26391 V BO_ANDROID: Main.onResume()
02-10 11:17:18.668 26391 26391 V BO_ANDROID: requestWakeupPermissions() background period: 0
02-10 11:17:18.668 26391 26391 V BO_ANDROID: AlertView received location null
02-10 11:17:18.668 26391 26391 D BO_ANDROID: AlertHandler: added first alert consumer
02-10 11:17:18.668 26391 26391 V BO_ANDROID: AlertView alertEventConsumer received AlertCancelEvent()
02-10 11:17:18.668 26391 26391 D BO_ANDROID: DataHandler: added first data consumer
02-10 11:17:18.669 26391 26391 V BO_ANDROID: LocationProvider.start() type: network
02-10 11:17:18.669 26391 26391 V BO_ANDROID: ManagerLocationProvider.start() background: false, type: network, minTime: 20000, minDistance: 50.0
02-10 11:17:18.674 26391 26391 V BO_ANDROID: AppService.configureServiceMode() realtime_data, restart_handler
02-10 11:17:18.674 26391 26391 V BO_ANDROID: HistoryController.setAppService(org.blitzortung.android.app.AppService@7dcd617)
02-10 11:17:18.674 26391 26391 D BO_ANDROID: Main.onResume() 2019-02-10 11:17:18.674 service: org.blitzortung.android.app.AppService@7dcd617
02-10 11:17:18.693 26391 26391 D BO_ANDROID: Main.onDataUpdate() received request started event
02-10 11:17:18.693 26391 26391 D BO_ANDROID: DataHandler.updateData() Parameters(region=1, rasterBaselength=0, intervalDuration=240, intervalOffset=0, countThreshold=0)
02-10 11:17:18.770 26391 26391 I Timeline: Timeline: Activity_idle id: android.os.BinderProxy@724ffbf time:499355422
02-10 11:17:19.631 26391 26391 V BO_ANDROID: MainPopupMenu.showPopupMenu()
02-10 11:17:20.530 26391 26391 D BO_ANDROID: updateVersionStatus() name=org.blitzortung.android.app, state=NO_UPDATE, configuredVersion=223, currentVersion=223
02-10 11:17:21.649 26391 26391 I BO_ANDROID: LocationHandler.sendLocationUpdate() location Location[network 55,981605,37,179575 acc=25 et=+19d13h7m53s136ms alt=0.0 vel=0.0 bear=0.0 {Bundle[mParcelledData.dataSize=80]}]
02-10 11:17:21.649 26391 26391 V BO_ANDROID: AlertHandler: received location Location[network 55,981605,37,179575 acc=25 et=+19d13h7m53s136ms alt=0.0 vel=0.0 bear=0.0 {Bundle[mParcelledData.dataSize=80]}] (was null)
02-10 11:17:21.650 26391 26412 V BO_ANDROID: AlertHandler.checkStrikes() strikes: false, location: true
02-10 11:17:21.650 26391 26391 V BO_ANDROID: AlertView received location Location[network 55,981605,37,179575 acc=25 et=+19d13h7m53s136ms alt=0.0 vel=0.0 bear=0.0 {Bundle[mParcelledData.dataSize=80]}]
02-10 11:17:21.669 26391 26391 V BO_ANDROID: AlertHandler.processResult() no result 
02-10 11:17:21.669 26391 26391 V BO_ANDROID: AlertHandler.broadcastEvent(AlertCancelEvent())
02-10 11:17:21.669 26391 26391 V BO_ANDROID: AlertView alertEventConsumer received AlertCancelEvent()
02-10 11:17:22.075 26391 29655 W BO_ANDROID: BlitzortungHttpDataProvider.readFromUrl() http://data.blitzortung.org/Data_1/Protected/Strokes/2019/02/10/04/10.log failed
02-10 11:17:22.076 26391 29655 W System.err: java.lang.RuntimeException: java.net.ProtocolException: Too many follow-up requests: 21
02-10 11:17:22.077 26391 29655 W System.err: at org.blitzortung.android.data.provider.blitzortung.BlitzortungHttpDataProvider.readFromUrl(BlitzortungHttpDataProvider.kt:91)
02-10 11:17:22.077 26391 29655 W System.err: at org.blitzortung.android.data.provider.blitzortung.BlitzortungHttpDataProvider.access$readFromUrl(BlitzortungHttpDataProvider.kt:40)
02-10 11:17:22.077 26391 29655 W System.err: at org.blitzortung.android.data.provider.blitzortung.BlitzortungHttpDataProvider$Retriever$getStrikes$strikes$1.invoke(BlitzortungHttpDataProvider.kt:174)
02-10 11:17:22.077 26391 29655 W System.err: at org.blitzortung.android.data.provider.blitzortung.BlitzortungHttpDataProvider$Retriever$getStrikes$strikes$1.invoke(BlitzortungHttpDataProvider.kt:148)
02-10 11:17:22.077 26391 29655 W System.err: at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:172)
02-10 11:17:22.077 26391 29655 W System.err: at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:132)
02-10 11:17:22.077 26391 29655 W System.err: at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156)
02-10 11:17:22.077 26391 29655 W System.err: at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:273)
02-10 11:17:22.077 26391 29655 W System.err: at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:265)
02-10 11:17:22.077 26391 29655 W System.err: at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:698)
02-10 11:17:22.077 26391 29655 W System.err: at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:728)
02-10 11:17:22.077 26391 29655 W System.err: at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:719)
02-10 11:17:22.078 26391 29655 W System.err: at org.blitzortung.android.data.provider.blitzortung.BlitzortungHttpDataProvider.retrieveData(BlitzortungHttpDataProvider.kt:119)
02-10 11:17:22.078 26391 29655 W System.err: at org.blitzortung.android.data.provider.blitzortung.BlitzortungHttpDataProvider.access$retrieveData(BlitzortungHttpDataProvider.kt:40)
02-10 11:17:22.078 26391 29655 W System.err: at org.blitzortung.android.data.provider.blitzortung.BlitzortungHttpDataProvider$Retriever.getStrikes(BlitzortungHttpDataProvider.kt:170)
02-10 11:17:22.078 26391 29655 W System.err: at org.blitzortung.android.data.DataHandler$FetchDataTask$doInBackground$1.invoke(DataHandler.kt:291)
02-10 11:17:22.078 26391 29655 W System.err: at org.blitzortung.android.data.DataHandler$FetchDataTask$doInBackground$1.invoke(DataHandler.kt:270)
02-10 11:17:22.078 26391 29655 W System.err: at org.blitzortung.android.data.provider.blitzortung.BlitzortungHttpDataProvider.retrieveData(BlitzortungHttpDataProvider.kt:145)
02-10 11:17:22.078 26391 29655 W System.err: at org.blitzortung.android.data.DataHandler$FetchDataTask.doInBackground(DataHandler.kt:287)
02-10 11:17:22.079 26391 29655 W System.err: at org.blitzortung.android.data.DataHandler$FetchDataTask.doInBackground(DataHandler.kt:270)
02-10 11:17:22.079 26391 29655 W System.err: at android.os.AsyncTask$2.call(AsyncTask.java:295)
02-10 11:17:22.079 26391 29655 W System.err: at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-10 11:17:22.079 26391 29655 W System.err: at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
02-10 11:17:22.079 26391 29655 W System.err: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
02-10 11:17:22.079 26391 29655 W System.err: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
02-10 11:17:22.079 26391 29655 W System.err: at java.lang.Thread.run(Thread.java:818)
02-10 11:17:22.079 26391 29655 W System.err: Caused by: java.net.ProtocolException: Too many follow-up requests: 21
02-10 11:17:22.079 26391 29655 W System.err: at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:401)
02-10 11:17:22.079 26391 29655 W System.err: at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:231)
02-10 11:17:22.079 26391 29655 W System.err: at org.blitzortung.android.data.provider.blitzortung.BlitzortungHttpDataProvider.readFromUrl(BlitzortungHttpDataProvider.kt:77)
02-10 11:17:22.079 26391 29655 W System.err: ... 25 more
02-10 11:17:22.095 26391 26391 V BO_ANDROID: LocationHandler.start() provider network already running
02-10 11:17:22.095 26391 26391 V BO_ANDROID: AppService.configureServiceMode() realtime_data
02-10 11:17:22.095 26391 26391 V BO_ANDROID: AlertHandler: received data FailedResult()
02-10 11:17:22.095 26391 26391 V BO_ANDROID: AlertHandler.broadcastEvent(AlertCancelEvent())
02-10 11:17:22.096 26391 26391 V BO_ANDROID: AlertView alertEventConsumer received AlertCancelEvent()
02-10 11:17:27.666 26391 26391 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
02-10 11:17:35.782 26391 26391 V BO_ANDROID: MainPopupMenu.showPopupMenu()
02-10 11:17:37.197 26391 26391 D BO_ANDROID: updateVersionStatus() name=org.blitzortung.android.app, state=NO_UPDATE, configuredVersion=223, currentVersion=223
```

**Comment by wuan** [comment]
The error 
```
02-10 11:17:22.075 26391 29655 W BO_ANDROID: BlitzortungHttpDataProvider.readFromUrl() http://data.blitzortung.org/Data_1/Protected/Strokes/2019/02/10/04/10.log failed
02-10 11:17:22.076 26391 29655 W System.err: java.lang.RuntimeException: java.net.ProtocolException: Too many follow-up requests: 21
```
appears, when the credentials are not correct. Please verify the Blitzortung.org username and password used.
